# Generated by Django 4.1 on 2023-02-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="profile1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="profile2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
